TimelineTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: TimelineTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: type
        AttributeType: S
      - AttributeName: username
        AttributeType: S
      - AttributeName: createdAt
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: typeGSI
        KeySchema:
          - AttributeName: type
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: usernameAndCreatedAtGSI
        KeySchema:
          - AttributeName: username
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
    # LocalSecondaryIndexes:
    #   - IndexName: timelineLSI
    #     KeySchema:
    #       - AttributeName: timelineId
    #         KeyType: HASH
    #     Projection:
    #       ProjectionType: ALL

